# For more information: https://github.com/julien-r44/adonis-sail
version: '3'

services:
  pgsql:
    image: 'postgres:16'
    container_name: pgsql
    ports:
      - '${PG_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${PG_PASSWORD:-secret}'
      POSTGRES_DB: '${PG_DB_NAME:-default}'
      POSTGRES_USER: '${PG_USER?:err}'
      POSTGRES_PASSWORD: '${PG_PASSWORD:-secret}'
    volumes:
      - 'sailpgsql:/var/lib/postgresql/data'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${PG_DB_NAME:-default}", "-U", "${PG_USER}"]
      retries: 3
      timeout: 5s

  mailpit:
    image: 'axllent/mailpit'
    container_name: 'mailpit'
    ports:
      - '${MAILPIT_PORT:-1025}:1025'
      - '${MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sailpgsql:
