name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm i -g pnpm @antfu/ni

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: nci

      - name: Lint
        run: nr lint

      # - name: Test
      #   run: nr test

      - name: Build
        run: nr build
